name: torrential_lib
description: An API wrapper for multiple torrent clients to remotely control torrents 
version: 0.0.2
homepage: https://github.com/nateshmbhat/torrential-lib

dependencies:
  http: ^0.12.0+2
  html: ^0.14.0+2

dev_dependencies:
  test: ^1.11.0

environment:
  sdk: ">=2.1.0 <2.0.0"